name: Build bob

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
          - os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
          - os: windows-latest
            goos: windows
            goarch: amd64
            ext: ".exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # Build CLI
      - name: Build CLI
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bob-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} ./cmd/cli/main.go

      # Build WASM
      - name: Build WASM
        run: |
          GOOS=js GOARCH=wasm go build -o bob-wasm-${{ matrix.goos }}-${{ matrix.goarch }}.wasm ./cmd/bob

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bob-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            bob-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
            bob-wasm-${{ matrix.goos }}-${{ matrix.goarch }}.wasm
